#
all: *
install:	all
	mkdir -p /usr/share/doc/linuxbuh.ru
	install -m 0644 *.desktop /usr/share/doc/linuxbuh.ru
	install -m 0644 *.desktop /usr/share/applications
	install -m 0644 *.png /usr/share/pixmaps




